# Generated by Django 5.1.15 on 2026-06-14 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text="Short unique identifier, e.g. 'ACME'", max_length=20, unique=True)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='gyrokernel.company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(help_text="Django app_label, e.g. 'accounting'", max_length=100, unique=True)),
                ('gyro_name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('state', models.CharField(choices=[('installed', 'Installed'), ('uninstalling', 'Uninstalling'), ('error', 'Error')], db_index=True, default='installed', max_length=20)),
                ('depends', models.JSONField(default=list, help_text='app_labels this app depends on')),
                ('category', models.CharField(default='Generic', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Installed App',
                'verbose_name_plural': 'Installed Apps',
                'ordering': ['gyro_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False, help_text='When True, value is masked in API responses.')),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Parameter',
                'verbose_name_plural': 'System Parameters',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('install', 'Install'), ('uninstall', 'Uninstall'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(default=dict, help_text='{"field_name": [old_value, new_value]}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gyrokernel.company')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gyrokernel__content_249257_idx'), models.Index(fields=['user', 'timestamp'], name='gyrokernel__user_id_2de2ef_idx'), models.Index(fields=['company', 'action'], name='gyrokernel__company_91897f_idx')],
            },
        ),
    ]
