# Generated by Django 5.1.15 on 2026-06-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyrokernel', '0002_country_currency_language_partnertag_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='path',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Materialized path — ancestor UUID hexes joined by '/', root first", max_length=4000),
        ),
    ]
